# Generated by Django 3.2 on 2022-11-24 11:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20221124_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='borrowed',
            new_name='borrower',
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ca110958-4a76-43d4-b7d1-f89f56fe9585'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
