# Generated by Django 3.2 on 2022-11-24 11:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20221124_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c72160dc-2603-46b7-8ac6-b9f2ed5d1fc4'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
